name: Maven Test on Self-Hosted GCP Runner

on:
  workflow_dispatch:

jobs:
  test-on-self-hosted:
    runs-on: self-hosted
    name: Self Hosted GCP VM

    steps:

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
         java-version: '17'
         distribution: 'temurin'

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Maven Run 1
        run: mvn clean compile

      - name: Maven Run 2
        run: mvn clean compile

      - name: Maven Run 3
        run: mvn clean compile

      - name: Maven Run 4
        run: mvn clean compile

      - name: Maven Run 5
        run: mvn clean compile
