name: Maven Test on GitHub Ubuntu Runner

on:
  workflow_dispatch:

jobs:
  test-on-github-hosted:
    runs-on: ubuntu-latest
    name: GitHub Hosted Ubuntu

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Maven Run 1
        run: mvn clean compile

      - name: Maven Run 2
        run: mvn clean compile

      - name: Maven Run 3
        run: mvn clean compile

      - name: Maven Run 4
        run: mvn clean compile

      - name: Maven Run 5
        run: mvn clean compile
